// Code generated by mockery v2.9.4. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockConnection is an autogenerated mock type for the Connection type
type MockConnection struct {
	mock.Mock
}

// GetConn provides a mock function with given fields:
func (_m *MockConnection) GetConn() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// SetConn provides a mock function with given fields: _a0
func (_m *MockConnection) SetConn(_a0 int) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
